function(soldat_generate_weapons output_directory)
  set(source_root "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/..")
  file(STRINGS "${source_root}/shared/Weapons.pas" source_lines)
  set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS
    "${source_root}/shared/Weapons.pas"
    "${source_root}/shared/Constants.pas"
    "${source_root}/shared/mechanics/Sprites.pas"
    "${source_root}/shared/mechanics/Things.pas"
    "${source_root}/shared/Anims.pas"
    "${source_root}/shared/Cvar.pas")
  set(source_fields Name Num FireMode ClipReload HitMultiply FireInterval Ammo ReloadTime Speed
    BulletStyle StartUpTime Bink MovementAcc BulletSpread Recoil Push InheritedVelocity
    ModifierHead ModifierChest ModifierLegs)
  set(c_fields name num fire_mode clip_reload hit_multiply fire_interval ammo reload_time speed
    bullet_style startup_time bink movement_acc bullet_spread recoil push inherited_velocity
    modifier_head modifier_chest modifier_legs)
  set(float_fields HitMultiply Speed MovementAcc BulletSpread Push InheritedVelocity
    ModifierHead ModifierChest ModifierLegs)
  set(section "")
  set(in_implementation FALSE)
  foreach(line IN LISTS source_lines)
    string(STRIP "${line}" line)
    if(line STREQUAL "implementation")
      set(in_implementation TRUE)
    endif()
    if(NOT in_implementation)
      if(line MATCHES "^([A-Z][A-Z0-9_]*)[ \t]*=[ \t]*([0-9]+);")
        set(constant_${CMAKE_MATCH_1} "${CMAKE_MATCH_2}")
      endif()
      continue()
    endif()
    if(line MATCHES "^procedure ([A-Za-z]+)")
      set(section "${CMAKE_MATCH_1}")
    endif()
    if(NOT section MATCHES "^(CreateWeaponsBase|CreateNormalWeapons|BuildWeapons)$")
      continue()
    endif()
    if(section STREQUAL "BuildWeapons" AND line MATCHES "^for WeaponIndex")
      set(section "")
      continue()
    endif()
    if(line MATCHES "^Gun := @Guns\\[([A-Z0-9]+)\\];")
      set(weapon "${CMAKE_MATCH_1}")
      if(section STREQUAL "CreateWeaponsBase")
        list(APPEND weapon_ids "${weapon}")
      endif()
    elseif(line MATCHES "^Gun\\.([A-Za-z]+)[ \t]*:=[ \t]*(.*);")
      set(field "${CMAKE_MATCH_1}")
      set(value "${CMAKE_MATCH_2}")
      if(NOT field IN_LIST source_fields)
        continue()
      endif()
      if(value MATCHES "^Guns\\[([A-Z0-9]+)\\]\\.([A-Za-z]+)$")
        set(value "${weapon_${CMAKE_MATCH_1}_${CMAKE_MATCH_2}}")
      elseif(DEFINED constant_${value})
        set(value "${constant_${value}}")
      elseif(value STREQUAL "True")
        set(value 1)
      elseif(value STREQUAL "False")
        set(value 0)
      endif()
      if(field STREQUAL "Name")
        if(NOT value MATCHES "^'([^']+)'$")
          message(FATAL_ERROR "Unrecognized weapon name: ${value}")
        endif()
        set(value "\"${CMAKE_MATCH_1}\"")
      elseif(NOT value MATCHES "^-?[0-9]+([.][0-9]+)?$")
        message(FATAL_ERROR "Unrecognized weapon value ${weapon}.${field}: ${value}")
      endif()
      set(weapon_${weapon}_${field} "${value}")
    endif()
  endforeach()
  list(LENGTH weapon_ids weapon_count)
  if(NOT weapon_count EQUAL constant_TOTAL_WEAPONS)
    message(FATAL_ERROR "Expected ${constant_TOTAL_WEAPONS} weapon definitions, found ${weapon_count}")
  endif()
  set(weapon_BARRETT_StartUpTime 0)
  set(weapon_RUGER77_MovementAcc 0.02)
  set(weapon_SPAS12_BulletSpread 0.7)
  set(generated "#include \"game.h\"\n#include \"generated_rules.h\"\n\nconst WeaponDef weapons[WEAPON_COUNT] = {\n")
  foreach(weapon IN LISTS weapon_ids)
    string(APPEND generated "    [${weapon}] = {\n")
    foreach(field c_field IN ZIP_LISTS source_fields c_fields)
      if(NOT DEFINED weapon_${weapon}_${field})
        if(weapon MATCHES "^(CLUSTERGRENADE|CLUSTER|THROWNKNIFE)$" AND field MATCHES "^Modifier")
          set(weapon_${weapon}_${field} 0)
        else()
          message(FATAL_ERROR "Missing source field ${weapon}.${field}")
        endif()
      endif()
      set(value "${weapon_${weapon}_${field}}")
      if(field IN_LIST float_fields)
        if(NOT value MATCHES "[.]")
          string(APPEND value ".0")
        endif()
        string(APPEND value "f")
      endif()
      string(APPEND generated "        .${c_field} = ${value},\n")
    endforeach()
    set(style "${weapon_${weapon}_BulletStyle}")
    if(style EQUAL constant_BULLET_STYLE_FRAGNADE OR style EQUAL constant_BULLET_STYLE_CLUSTERNADE)
      set(timeout GRENADE_TIMEOUT)
    elseif(style EQUAL constant_BULLET_STYLE_FLAME)
      set(timeout FLAMER_TIMEOUT)
    elseif(style EQUAL constant_BULLET_STYLE_PUNCH OR style EQUAL constant_BULLET_STYLE_KNIFE)
      set(timeout MELEE_TIMEOUT)
    elseif(style EQUAL constant_BULLET_STYLE_M2)
      set(timeout M2BULLET_TIMEOUT)
    else()
      set(timeout BULLET_TIMEOUT)
    endif()
    string(APPEND generated "        .timeout = SRC_${timeout}\n    },\n")
  endforeach()
  string(APPEND generated "};\n")
  file(MAKE_DIRECTORY "${output_directory}")
  file(WRITE "${output_directory}/weapons_generated.c" "${generated}")

  file(READ "${source_root}/shared/Constants.pas" constants)
  file(READ "${source_root}/shared/mechanics/Sprites.pas" sprites)
  file(READ "${source_root}/shared/Anims.pas" animations)
  file(READ "${source_root}/shared/Cvar.pas" cvars)
  file(READ "${source_root}/shared/mechanics/Things.pas" things)
  set(rules_source "${constants}\n${sprites}")
  set(rule_names SECOND MAX_OLDPOS DEFAULTAIMDIST SNIPERAIMDIST CROUCHAIMDIST DEFAULT_HEALTH BULLET_TIMEOUT GRENADE_TIMEOUT M2BULLET_TIMEOUT
    FLAMER_TIMEOUT MELEE_TIMEOUT MAX_INACCURACY EXPLOSION_IMPACT_MULTIPLY
    RUNSPEED RUNSPEEDUP FLYSPEED JUMPSPEED CROUCHRUNSPEED PRONESPEED ROLLSPEED JUMPDIRSPEED
    JETSPEED SURFACECOEFX CROUCHMOVESURFACECOEFX MAX_VELOCITY GRENADE_SURFACECOEF
    M79GRENADE_EXPLOSION_RADIUS FRAGGRENADE_EXPLOSION_RADIUS CLUSTERGRENADE_EXPLOSION_RADIUS
    PART_RADIUS EXPLOSION_ANIMS SMOKE_ANIMS BULLETTRAIL GUNRESISTTIME FLAG_TIMEOUT
    GUN_RADIUS BOW_RADIUS KIT_RADIUS DEFAULTVEST CLUSTER_GRENADES FLAMERBONUSTIME
    PREDATORBONUSTIME BERSERKERBONUSTIME FLAMERBONUS_RANDOM PREDATORBONUS_RANDOM
    VESTBONUS_RANDOM BERSERKERBONUS_RANDOM CLUSTERBONUS_RANDOM PREDATORALPHA
    DISCONNECTION_TIME HEADCHOPDEATHHEALTH BRUTALDEATHHEALTH EXPLOSION_DEADIMPACT_MULTIPLY
    LESSBLEED_TIME NOBLEED_TIME MINMOVEDELTA MULTIKILLINTERVAL TOUCHDOWN_RADIUS BASE_RADIUS
    FLAGTHROW_POWER HTF_SEC_POINT WAVERESPAWN_TIME_MULITPLIER DEFAULT_MAPCHANGE_TIME
    FLAG_PART_RADIUS THING_PUSH_MULTIPLIER THING_COLLISION_COOLDOWN DEFAULT_CEASEFIRE_TIME ILUMINATESPEED)
  set(rules "#ifndef SOLDAT3D_GENERATED_RULES_H\n#define SOLDAT3D_GENERATED_RULES_H\n\n")
  foreach(name IN LISTS rule_names)
    string(REGEX MATCH "[\n \t]${name}[ \t]*=[ \t]*([^;\n]+);" match "${rules_source}")
    if(NOT match)
      message(FATAL_ERROR "Missing source constant ${name}")
    endif()
    string(STRIP "${CMAKE_MATCH_1}" expression)
    string(REGEX REPLACE "([A-Z][A-Z0-9_]*)" "SRC_\\1" expression "${expression}")
    string(APPEND rules "#define SRC_${name} (${expression})\n")
  endforeach()
  foreach(name IN ITEMS respawntime respawntime_minwave respawntime_maxwave dm_limit pm_limit tm_limit
      rm_limit ctf_limit inf_limit inf_bluelimit inf_redaward htf_limit htf_pointstime timelimit)
    string(REGEX MATCH "sv_${name} := TIntegerCvar.Add\\('sv_${name}', '[^']*', ([0-9]+)," match "${cvars}")
    if(NOT match)
      message(FATAL_ERROR "Missing source default sv_${name}")
    endif()
    string(TOUPPER "${name}" constant)
    string(APPEND rules "#define SRC_${constant} (${CMAKE_MATCH_1})\n")
  endforeach()
  string(REGEX MATCH "Thing\\[i\\].Skeleton.VDamping := ([0-9.]+);" match "${things}")
  if(NOT match)
    message(FATAL_ERROR "Missing source flag damping")
  endif()
  string(APPEND rules "#define SRC_FLAG_DAMPING (${CMAKE_MATCH_1}f)\n")
  string(REGEX MATCH "Thing\\[i\\].Radius := ([0-9]+);" match "${things}")
  if(NOT match)
    message(FATAL_ERROR "Missing source flag radius")
  endif()
  string(APPEND rules "#define SRC_FLAG_RADIUS (${CMAKE_MATCH_1})\n")
  set(thing_names DESERT_EAGLE HK_MP5 AK74 STEYR_AUG SPAS12 RUGER77 M79 BARRET_M82A1 MINIMI MINIGUN
    USSOCOM COMBAT_KNIFE CHAINSAW LAW RAMBO_BOW MEDICAL_KIT GRENADE_KIT FLAMER_KIT PREDATOR_KIT
    VEST_KIT BERSERK_KIT CLUSTER_KIT)
  foreach(name IN LISTS thing_names)
    string(FIND "${things}" "OBJECT_${name}:" begin)
    if(begin LESS 0)
      message(FATAL_ERROR "Missing original thing ${name}")
    endif()
    string(SUBSTRING "${things}" ${begin} -1 tail)
    string(FIND "${tail}" "end;" end)
    string(SUBSTRING "${tail}" 0 ${end} block)
    foreach(field IN ITEMS VDamping Gravity)
      string(REGEX MATCH "Skeleton[.]${field} := ([0-9.]+)" match "${block}")
      if(NOT match)
        message(FATAL_ERROR "Missing thing ${name}.${field}")
      endif()
      string(TOUPPER "${field}" field_name)
      string(APPEND rules "#define SRC_THING_${name}_${field_name} (${CMAKE_MATCH_1}f)\n")
    endforeach()
  endforeach()
  string(REGEX MATCH "sv_gravity := TSingleCvar.Add\\('sv_gravity', 'Gravity', ([0-9.]+)," match "${cvars}")
  if(NOT match)
    message(FATAL_ERROR "Missing source gravity default")
  endif()
  string(APPEND rules "#define SRC_GRAV (${CMAKE_MATCH_1}f)\n")
  string(REGEX MATCH "SpriteParts.EDamping := ([0-9.]+);" match "${animations}")
  if(NOT match)
    message(FATAL_ERROR "Missing source player damping")
  endif()
  string(APPEND rules "#define SRC_EDAMPING (${CMAKE_MATCH_1}f)\n")
  string(REGEX MATCH "Skeleton.Gravity := ([0-9.]+) [*] GRAV;" match "${animations}")
  if(NOT match)
    message(FATAL_ERROR "Missing source ragdoll gravity")
  endif()
  string(APPEND rules "#define SRC_RAGDOLL_GRAVITY (SRC_GRAV * ${CMAKE_MATCH_1}f)\n")
  string(REGEX MATCH "Skeleton.VDamping := ([0-9.]+);" match "${animations}")
  if(NOT match)
    message(FATAL_ERROR "Missing source ragdoll damping")
  endif()
  string(APPEND rules "#define SRC_RAGDOLL_DAMPING (${CMAKE_MATCH_1}f)\n")
  string(REGEX MATCH "BoxSkeleton.LoadPOObject\\('objects/kit.po', ([0-9.]+)\\);" match "${animations}")
  if(NOT match)
    message(FATAL_ERROR "Missing source pickup scale")
  endif()
  string(APPEND rules "#define SRC_KIT_WIDTH (5 * ${CMAKE_MATCH_1}f / 1.2f)\n#define SRC_KIT_HEIGHT (4 * ${CMAKE_MATCH_1}f)\n")
  string(REGEX MATCH "BulletParts.EDamping := ([0-9.]+);" match "${animations}")
  if(NOT match)
    message(FATAL_ERROR "Missing source projectile damping")
  endif()
  string(APPEND rules "#define SRC_BULLET_DAMPING (${CMAKE_MATCH_1}f)\n")
  string(REGEX MATCH "BulletParts.Gravity := GRAV [*] ([0-9.]+);" match "${animations}")
  if(NOT match)
    message(FATAL_ERROR "Missing source projectile gravity")
  endif()
  string(APPEND rules "#define SRC_BULLET_GRAVITY (SRC_GRAV * ${CMAKE_MATCH_1}f)\n")
  set(animation_names JUMP SIDEJUMP ROLL ROLLBACK PRONEMOVE PRONE GETUP RELOAD CHANGE PUNCH)
  set(animation_files skok skokwbok skokdolobrot skokdolobrottyl lezyidzie lezy wstaje laduje change bije)
  foreach(name filename IN ZIP_LISTS animation_names animation_files)
    set(path "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/assets/anims/${filename}.poa")
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${path}")
    file(STRINGS "${path}" frames REGEX "^NEXTFRAME$")
    list(LENGTH frames frame_count)
    math(EXPR frame_count "${frame_count} + 1")
    string(APPEND rules "#define SRC_${name}_FRAMES (${frame_count})\n")
  endforeach()
  set(art_path "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/assets/mod.ini")
  set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${art_path}")
  file(READ "${art_path}" art_config)
  string(REGEX MATCH "DefaultScale=([0-9.]+)" match "${art_config}")
  if(NOT match)
    message(FATAL_ERROR "Missing original asset scale")
  endif()
  string(APPEND rules "#define SRC_ART_SCALE (${CMAKE_MATCH_1}f)\n\n#endif\n")
  file(WRITE "${output_directory}/generated_rules.h" "${rules}")
endfunction()
